<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Busee</title>
    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <meta name="description" content="描述 celery异步调用，经常会传一些比较大的数据，调用比较多会经常出现连接被关闭
错误内容 File &#34;/usr/local/lib/python3.6/dist-packages/celery/result.py&#34;, line 228, in get on_message=on_message, File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 193, in wait_for_pending for _ in self._wait_for_pending(result, **kwargs): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 260, in _wait_for_pending on_interval=on_interval): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 56, in drain_events_until yield self.wait_for(p, wait, timeout=1) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 65, in wait_for wait(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/redis.py&#34;, line 127, in drain_events message = self._pubsub.get_message(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3565, in get_message response = self.parse_response(block=False, timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3451, in parse_response if not block and not conn.">
    <meta name="generator" content="Hugo 0.121.2">
    
    
    
    
      <meta name="robots" content="noindex, nofollow">
    

    
<link rel="stylesheet" href="/ananke/css/main.min.css" >



    

    
      

    

    

    
      <link rel="canonical" href="https://www.yongqingking.top/posts/tensorflow/redis%E4%BF%AE%E6%94%B9%E7%BC%93%E5%AD%98%E9%99%90%E5%88%B6client-output-buffer-limit/">
    

    <meta property="og:title" content="" />
<meta property="og:description" content="描述 celery异步调用，经常会传一些比较大的数据，调用比较多会经常出现连接被关闭
错误内容 File &#34;/usr/local/lib/python3.6/dist-packages/celery/result.py&#34;, line 228, in get on_message=on_message, File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 193, in wait_for_pending for _ in self._wait_for_pending(result, **kwargs): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 260, in _wait_for_pending on_interval=on_interval): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 56, in drain_events_until yield self.wait_for(p, wait, timeout=1) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 65, in wait_for wait(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/redis.py&#34;, line 127, in drain_events message = self._pubsub.get_message(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3565, in get_message response = self.parse_response(block=False, timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3451, in parse_response if not block and not conn." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://www.yongqingking.top/posts/tensorflow/redis%E4%BF%AE%E6%94%B9%E7%BC%93%E5%AD%98%E9%99%90%E5%88%B6client-output-buffer-limit/" /><meta property="article:section" content="posts" />



<meta itemprop="name" content="">
<meta itemprop="description" content="描述 celery异步调用，经常会传一些比较大的数据，调用比较多会经常出现连接被关闭
错误内容 File &#34;/usr/local/lib/python3.6/dist-packages/celery/result.py&#34;, line 228, in get on_message=on_message, File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 193, in wait_for_pending for _ in self._wait_for_pending(result, **kwargs): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 260, in _wait_for_pending on_interval=on_interval): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 56, in drain_events_until yield self.wait_for(p, wait, timeout=1) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 65, in wait_for wait(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/redis.py&#34;, line 127, in drain_events message = self._pubsub.get_message(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3565, in get_message response = self.parse_response(block=False, timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3451, in parse_response if not block and not conn.">

<meta itemprop="wordCount" content="187">
<meta itemprop="keywords" content="" /><meta name="twitter:card" content="summary"/><meta name="twitter:title" content=""/>
<meta name="twitter:description" content="描述 celery异步调用，经常会传一些比较大的数据，调用比较多会经常出现连接被关闭
错误内容 File &#34;/usr/local/lib/python3.6/dist-packages/celery/result.py&#34;, line 228, in get on_message=on_message, File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 193, in wait_for_pending for _ in self._wait_for_pending(result, **kwargs): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 260, in _wait_for_pending on_interval=on_interval): File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 56, in drain_events_until yield self.wait_for(p, wait, timeout=1) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 65, in wait_for wait(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/redis.py&#34;, line 127, in drain_events message = self._pubsub.get_message(timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3565, in get_message response = self.parse_response(block=False, timeout=timeout) File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3451, in parse_response if not block and not conn."/>

	
  </head>

  <body class="ma0 avenir bg-near-white">

    
   
  

  <header>
    <div class="bg-black">
      <nav class="pv3 ph3 ph4-ns" role="navigation">
  <div class="flex-l justify-between items-center center">
    <a href="/" class="f3 fw2 hover-white no-underline white-90 dib">
      
        Busee
      
    </a>
    <div class="flex-l items-center">
      

      
        <ul class="pl0 mr3">
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/" title="首页 page">
              首页
            </a>
          </li>
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/posts/" title="归档 page">
              归档
            </a>
          </li>
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/categories/" title="分类 page">
              分类
            </a>
          </li>
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/tags/" title="标签 page">
              标签
            </a>
          </li>
          
        </ul>
      
      
<div class="ananke-socials">
  
</div>

    </div>
  </div>
</nav>

    </div>
  </header>



    <main class="pb7" role="main">
      
  
  <article class="flex-l flex-wrap justify-between mw8 center ph3">
    <header class="mt4 w-100">
      <aside class="instapaper_ignoref b helvetica tracked ttu">
          
        Posts
      </aside>
      










  <div id="sharing" class="mt3 ananke-socials">
    
  </div>


      <h1 class="f1 athelas mt3 mb1"></h1>
      
      
      

      
      
    </header>
    <div class="nested-copy-line-height lh-copy serif f4 nested-links mid-gray pr4-l w-two-thirds-l"><h1 id="描述">描述</h1>
<p>celery异步调用，经常会传一些比较大的数据，调用比较多会经常出现连接被关闭</p>
<h1 id="错误内容">错误内容</h1>
<pre tabindex="0"><code>  File &#34;/usr/local/lib/python3.6/dist-packages/celery/result.py&#34;, line 228, in get
    on_message=on_message,
  File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 193, in wait_for_pending
    for _ in self._wait_for_pending(result, **kwargs):
  File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 260, in _wait_for_pending
    on_interval=on_interval):
  File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 56, in drain_events_until
    yield self.wait_for(p, wait, timeout=1)
  File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/asynchronous.py&#34;, line 65, in wait_for
    wait(timeout=timeout)
  File &#34;/usr/local/lib/python3.6/dist-packages/celery/backends/redis.py&#34;, line 127, in drain_events
    message = self._pubsub.get_message(timeout=timeout)
  File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3565, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File &#34;/usr/local/lib/python3.6/dist-packages/redis/client.py&#34;, line 3451, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File &#34;/usr/local/lib/python3.6/dist-packages/redis/connection.py&#34;, line 729, in can_read
    return self._parser.can_read(timeout)
  File &#34;/usr/local/lib/python3.6/dist-packages/redis/connection.py&#34;, line 313, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File &#34;/usr/local/lib/python3.6/dist-packages/redis/connection.py&#34;, line 223, in can_read
    raise_on_timeout=False)
  File &#34;/usr/local/lib/python3.6/dist-packages/redis/connection.py&#34;, line 193, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
</code></pre><h1 id="redis日志varlogredisredis-serverlog">redis日志/var/log/redis/redis-server.log</h1>
<pre tabindex="0"><code>1163:M 27 Apr 17:12:17.163 # Client id=93 addr=172.17.0.3:41098 fd=15 name= age=70 idle=1 flags=N db=0 sub=4 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=87 oll=1 omem=8388648 events=rw cmd=subscribe scheduled to be closed ASAP for overcoming of output buffer limits.
</code></pre><h1 id="修改配置参数解决">修改配置参数解决</h1>
<pre tabindex="0"><code># /etc/redis/redis.conf
# client-output-buffer-limit &lt;class&gt; &lt;hard limit&gt; &lt;soft limit&gt; &lt;soft seconds&gt;
# 条件1 hard limit表示超过该数值, server直接关闭连接
# 条件2 soft limit表示超过该数值，持续soft seconds秒, server关闭连接

# 默认
client-output-buffer-limit pubsub 32mb 8mb 60

# 改为(0表示不限制)
client-output-buffer-limit pubsub 0 0 0
</code></pre><ul class="pa0">
  
</ul>
<div class="mt6 instapaper_ignoref">
      
      
      </div>
    </div>

    <aside class="w-30-l mt6-l">




</aside>

  </article>

    </main>
    <footer class="bg-black bottom-0 w-100 pa3" role="contentinfo">
  <div class="flex justify-between">
  <a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href="https://www.yongqingking.top/" >
    &copy;  Busee 2024 
  </a>
    <div>
<div class="ananke-socials">
  
</div>
</div>
  </div>
</footer>

  </body>
</html>
